### ISSUE TITLE
Difference to data sets contained in package plm

### ISSUE THREAD

**Issue by tappek** [pachadotdev/baltagi#1]
This looks nice to have the data sets as a dedicated package. However, may I ask if there is a difference to the data sets as contained in package `plm`?

**Comment by pachadotdev** [comment]
> This looks nice to have the data sets as a dedicated package. However, may I ask if there is a difference to the data sets as contained in package `plm`?

I made this for a workshop. I tend to document everything with detail and use factor type and int variables a lot. Besides it, it is the same.
